# 端口
server:
  port: 10001

# eureka config
eureka:
  client:
    # 表示是否注册自身到eureka服务器
    register-with-eureka: false
    # 是否从eureka上获取注册信息
    fetch-registry: false
    # 注册地址
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:10001/eureka/

# security config
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
