# 端口
server:
  port: 10020

# 服务名称
spring:
  application:
    name: boot-redis

# eureka config
eureka:
  instance:
    # 是否注册ip
    ip-address: true
  client:
    # 注册地址
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:10001/eureka/
