# 端口
server:
  port: 10030

# 服务名称
spring:
  application:
    name: boot-demo

# eureka config
eureka:
  instance:
    # 是否注册ip
    ip-address: true
  client:
    # 注册地址
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:10001/eureka/

#feign客户端启动hystrix断路保护
feign:
  hystrix:
    enabled: true

# timeout config
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 480000
