# 端口
server:
  port: 10010

# 服务名称
spring:
  application:
    name: boot-zuul

# eureka config
eureka:
  instance:
    # 是否注册ip
    ip-address: true
  client:
    # 注册地址
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:10001/eureka/

# timeout config
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 480000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    boot-demo:
      service-id: boot-demo
      path: /demo/**